apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    version: "{{ .Chart.Version }}"
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        provider: fabric8
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: "{{ .Chart.Version }}"
    spec:
      containers:
      - name: helloworld
        image: "{{ .Values.helloworld.image.name }}:latest"
        imagePullPolicy: {{ .Values.helloworld.image.pullPolicy }}
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
        securityContext:
          privileged: false
