apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helloworld-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: helloworld-external-secret
  data:
  - secretKey: {{ .Values.helloworld.externalsecrets.secretkey.key }}
    remoteRef:
      key: {{ .Values.helloworld.externalsecrets.remoteref.key }}
      property: {{ .Values.helloworld.externalsecrets.remoteref.property }}
    