apiVersion: v1
kind: Secret
metadata:
  name: helloworld
  labels:
    app: helloworld
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
  annotations:
    "avp.kubernetes.io/path": {{ .Values.helloworld.secrets.path | quote }}     
type: Opaque
data:
  secret1: {{ .Values.helloworld.secrets.secret1 | quote }}
  secret2: {{ .Values.helloworld.secrets.secret2 | quote }}