apiVersion: v1
entries:
  helloworld:
  - apiVersion: v1
    created: "2024-11-12T15:31:33.915167494+01:00"
    description: helloworld chart
    digest: 47127bad21962618348b80960ba55112785aa0620c8b6956fdd5877bf4c4c1b7
    home: https://s3.dev.thomaslochet.me/helm
    name: helloworld
    urls:
    - https://s3.dev.thomaslochet.me/helm/helloworld-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    created: "2024-11-12T15:31:33.901110237+01:00"
    description: helloworld chart
    digest: f1b88845e6c1cad3be012f809706b874699d3f074d6b3397fdb8624f738e59f2
    home: https://s3.dev.thomaslochet.me/helm
    name: helloworld
    urls:
    - https://s3.dev.thomaslochet.me/helm/helloworld-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    created: "2024-11-12T15:31:33.889467567+01:00"
    description: helloworld chart
    digest: 3c93af282b4859b0658bf4ac3163def3469ea7723a03158d347f244285b854be
    home: https://s3.dev.thomaslochet.me/helm
    name: helloworld
    urls:
    - https://s3.dev.thomaslochet.me/helm/helloworld-1.0.2.tgz
    version: 1.0.2
generated: "2024-11-12T15:31:33.874817761+01:00"
