helloworld:
  namespace: thomaslochet
  image:
    name: nginx
    tag: latest
    pullPolicy: IfNotPresent
  secrets:
    path: "helloworld/data/thomaslochet"
    secret1: <secret1>
    secret2: <secret2>