helloworld:
  namespace: thomaslochet
  image:
    name: nginx
    tag: latest
    pullPolicy: IfNotPresent
  secrets:
    path: 
    secret1: secret1
    secret2: secret2
  externalsecrets:
    secretkey:
      key: foo
    remoteref:
      key: infra/ovh/prod
      property: application_key